
image: gitpod/workspace-java-17

tasks:
  - init: ./mvnw install -DskipTests=false

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven
    - Pivotal.vscode-boot-dev-pack
